services:
  mysql:
    image: mysql:8
    restart: always
    env_file:
      - ./backend/mysql.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"  # Puerto host:contenedor
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  backend:
    build: ./backend
    restart: always
    depends_on:
      - mysql
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    networks:
      - backend

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true

volumes:
  mysql_data:

networks:
  backend: